---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wenwenjie.
--- DateTime: 2021/11/3 14:56
---
--- 链表类
local LinkList = {}

--- 创建一个链表
function LinkList:new()
    local list = {}
    setmetatable(list, self)
    self.__index = function(tMain, key)
        --print(tMain, list, self, key)
        if type(self[key]) ~= 'function' then
            -- 不是函数时，返回具体子类对象的字段
            return rawget(list, key)
        else
            -- 为函数时，返回父类函数
            return rawget(self, key)
        end
    end
   return list
end

--- 从表头插入元素
function LinkList:add(val)
    self = {next = self, val = val}
end

--- 遍历链表
function LinkList:showAll()
    local p = self
    print("开始遍历", self)
    local count = 1;
    while p do
        print(count, p, p.val)
        count = count + 1
        p = p.next
    end
    print("结束遍历", self)
end

local list = LinkList:new()
list:showAll()
list:add(1)
list:showAll()
list:add(2)
list:showAll()
print("----------")
local list1 = LinkList:new()
list1:showAll()
list1:add(1)
list1:showAll()
list1:add(2)
list1:showAll()
